name: github-actions-test
on: [push]
jobs: 
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: echo "Hello World. This is my first CI workflow"
      - name: Install Repo and Dependencies
        run: |
          npm install --save-dev
    #  - name: Start the Appium Server
    #    run: ./node_modules/.bin/appium --log-timestamp --log-no-colors --allow-insecure chromedriver_autodownload > appium.log &
