name: github-actions-test
on: [push]
jobs: 
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: echo "Hello World. This is my first CI workflow"
      - name: Install and Run Appium Server
        uses: moatazeldebsy/appium-server-gitHub-action@V1.0.4
